### ISSUE TITLE
Maintain view of map extent

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/dash-dv-explorer#20]
Paraphrased from @faronium

> Resetting any display options kicks the map back out to full zoom. That may be annoying to any user trying to zero in on a region of interest (which presumably will be *most* of our users).

**Comment by nannau** [comment]
I've noticed this too. It _might_ [be a straightforward fix](https://stackoverflow.com/questions/46075960/live-updating-only-the-data-in-dash-plotly).
