### ISSUE TITLE
Hover view values

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/dash-dv-explorer#21]
This may not be possible for a number of reasons, but I'll document it here for posterity. From @faronium :

> I like the hover-view for raster values. Is it possible to give the
> station value as well when the cursor is over a pixel with both or
> within some buffer?

**Comment by nannau** [comment]
I think this already happens with stations turned ON.

**Comment by jameshiebert** [comment]
Didn't you take that out because downloading the station data was too expensive and caused a 60+ second load time? Or am I thinking of something else.

**Comment by nannau** [comment]
The station data isn't a big deal, it was displaying any given raster cell's true Lat/Lon by looking it up in a reference grid that was very expensive. i.e. each DV field had to load the field (~1500x1500 grids) plus 2x(~1500x1500) lat/lon reference grids. Additionally, it was displaying the rotated lat and rotated lon in a similar fashion. So restricting raster cells to only display the data field was the best option. 

If, in the future, there's a movement towards WGS84 coordinates, it might be worth it to look into [plotly's Mapbox tools](https://plotly.com/python/scattermapbox/)
