### ISSUE TITLE
Assets missing from the repo

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/dash-dv-explorer#22]
The [config file](https://github.com/pacificclimate/dash-dv-explorer/blob/tablec2/config.yml) refers to asset directories for [`reconstructions`](https://github.com/pacificclimate/dash-dv-explorer/blob/tablec2/config.yml#L34) and [`ensemble`](https://github.com/pacificclimate/dash-dv-explorer/blob/tablec2/config.yml#L35), but those directories don't seem to be in the repository. Without them we don't have the data to deploy an instance of the DVE.

**Comment by jameshiebert** [comment]
Likewise for `assets/data/stations/`.

**Comment by rod-glover** [comment]
The following assets are still missing from the repo:
- 
- dve/data/model_inputs
- dve/data/reconstructions
- dve/data/station_inputs
- dve/data/tables

**Comment by rod-glover** [comment]
That merged PR includes the description "Removes data from assets." Hmm.

**Comment by rod-glover** [comment]
Since some of the absent data files are quite large, the better choice is to store them on /storage/data and mount them to the Docker container when it is run. For now, we'll just do that for the 4 data directories above, and leave the other 2 within the repo.
